'use client';

import React, { ChangeEvent } from 'react';
import './globals.css';
import { darkTheme, lightTheme } from './theme/themes';

import { CssBaseline, ThemeProvider } from '@mui/material';
import { LocalizationProvider} from '@mui/x-date-pickers'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  let [useDarkTheme, setUseDarkTheme] = React.useState(false);
  let [theme, setTheme] = React.useState(useDarkTheme ? darkTheme : lightTheme);

  const changeThemeHandler = (target: ChangeEvent, currentValue: boolean) => {
    setUseDarkTheme(currentValue);
    setTheme(currentValue ? darkTheme : lightTheme);
  };

  return (
    <html lang='en'>
    <head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </head>
    <ThemeProvider theme={theme}>

      <CssBaseline />
      <body id='__next'>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          {children}
        </LocalizationProvider>
      </body>

    </ThemeProvider>
    </html>
  );
}
